### ISSUE TITLE
Add BlobFile

### ISSUE THREAD

**Issue by garrettjstevens** [cmdcolin/generic-filehandle#1]
Could add a filehandle for file blobs, based on https://github.com/GMOD/jbrowse/blob/31f972f631489bb339c6e5212243a048ed84b65f/src/JBrowse/Model/FileBlob.js. I'm willing to take a shot at a PR if you think it fits in here.

**Comment by cmdcolin** [comment]
I think this would be good to have, someone requested exactly this for @gmod/bbi and it was kind of the motivation to create this module... to make such things standardized

**Comment by cmdcolin** [comment]
xref https://github.com/GMOD/bbi-js/issues/11
